extract: 
  model_path: ""
  log_path: ""
  target_cities:
    - Sydney
    - Melbourne
  api_urls:
    salesResults: https://api.domain.com.au/v1/salesResults/
    salesResults_listings: https://api.domain.com.au/v1/salesResults/{city}/listings
load: 
  chunksize: 1000
transform: 
  model_path: ""
meta: 
  log_table: "pipeline_logs"