extract: 
  log_path: ""
  target_cities:
    - Sydney
    - Melbourne
    - Adelaide
  api_urls:
    sales_results: https://api.domain.com.au/v1/salesResults/{city}
    sales_listings: https://api.domain.com.au/v1/salesResults/{city}/listings
load: 
  mode: "upsert"
  chunksize: 1000
  key_columns:
    sales_results:
      - city
      - lastModifiedDateTime
    sales_listings:
      - id
      - propertyDetailsUrl
      - result
transform: 
  model_path: "domain/models/"
meta: 
  log_table: "pipeline_logs"